---
kind: pipeline
type: kubernetes
name: debian-build

steps:
  - name: build
    image: debian:testing

    settings:
      registry: gitea.hedron.io
      username:
        from_secret: username
      password:
        from_secret: password
      repo: gitea.hedron.io/jtgans/g13gui
      tags:
        - latest
      platform: linux/amd64
      mtu: 1000

    commands:
      - apt-get update
      - touch /etc/pbuilderrc
      - apt-get install -y devscripts python3 build-essential git-buildpackage appstream dh-sequence-python3 meson
      - make

  - name: publish
    image: plugins/github-release

    settings:
      api_key:
        from_secret: github_token
      repo_owner: jtgans
      repo_name: g13gui
      draft: true
      files:
        - build/*
      checksum:
        - sha256
      depends_on:
        - build
    when:
      event:
        - tag
      ref:
        include:
          - "refs/tags/*"

