---
kind: pipeline
type: drone
name: archlinux

steps:
  - name: build
    image: archlinux:latest

    settings:
      registry: gitea.hedron.io
      username:
        from_secret: username
      password:
        from_secret: password
      repo: gitea.hedron.io/jtgans/g13gui
      tags:
        - latest
      platform: linux/amd64
      mtu: 1000

    commands:
      - tools/dockerbuild.sh archlinux

  - name: test
    image: archlinux:latest

    depends_on:
      - build

    commands:
      - pacman -Syu --noconfirm
      - pacman -U --noconfirm build/g13gui*.zst
      - python3 -m g13gui.tests

---
kind: pipeline
type: drone
name: debian

steps:
  - name: build
    image: debian:unstable

    settings:
      registry: gitea.hedron.io
      username:
        from_secret: username
      password:
        from_secret: password
      repo: gitea.hedron.io/jtgans/g13gui
      tags:
        - latest
      platform: linux/amd64
      mtu: 1000

    commands:
      - tools/dockerbuild.sh debian

  - name: test
    image: debian:unstable

    depends_on:
      - build

    commands:
      - apt-get update
      - apt-get -fy install ./build/g13*.deb
      - python3 -m g13gui.tests

---
kind: pipeline
type: drone
name: fedora

steps:
  - name: build
    image: fedora:latest

    settings:
      registry: gitea.hedron.io
      username:
        from_secret: username
      password:
        from_secret: password
      repo: gitea.hedron.io/jtgans/g13gui
      tags:
        - latest
      platform: linux/amd64
      mtu: 1000

    commands:
      - tools/dockerbuild.sh fedora

  - name: test
    image: fedora:latest

    depends_on:
      - build

    commands:
      - dnf install -y ./build/g13gui*.rpm
      - python3 -m g13gui.tests

